import Foundation
import SwiftUI

// MARK: - App language

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case english = "en"
    case german = "de"
    case french = "fr"
    case spanish = "es"

    var id: String { rawValue }

    var title: String {
        switch self {
        case .system: return LanguageManager.shared.localize("settings.language.system")
        case .english: return "English"
        case .german: return "Deutsch"
        case .french: return "Français"
        case .spanish: return "Español"
        }
    }
}

// MARK: - Appearance

enum AppAppearance: String, CaseIterable, Identifiable {
    case system
    case light
    case dark

    var id: String { rawValue }

    var title: String {
        switch self {
        case .system: return LanguageManager.shared.localize("settings.appearance.system")
        case .light: return LanguageManager.shared.localize("settings.appearance.light")
        case .dark: return LanguageManager.shared.localize("settings.appearance.dark")
        }
    }

    var colorScheme: ColorScheme? {
        switch self {
        case .system: return nil
        case .light: return .light
        case .dark: return .dark
        }
    }
}

// MARK: - Language manager

final class LanguageManager: ObservableObject {
    static let shared = LanguageManager()

    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: Keys.language) }
    }

    private enum Keys {
        static let language = "appLanguage"
    }

    private init() {
        let raw = UserDefaults.standard.string(forKey: Keys.language)
        language = raw.flatMap(AppLanguage.init(rawValue:)) ?? .system
    }

    func setLanguage(_ newLanguage: AppLanguage) {
        guard newLanguage != language else { return }
        language = newLanguage
    }

    private var active: AppLanguage {
        language == .system ? systemLanguage : language
    }

    private var systemLanguage: AppLanguage {
        let code = Locale.preferredLanguages.first?.lowercased() ?? "en"
        if code.hasPrefix("de") { return .german }
        if code.hasPrefix("fr") { return .french }
        if code.hasPrefix("es") { return .spanish }
        return .english
    }

    var locale: Locale {
        Locale(identifier: active.rawValue)
    }

    func localize(_ key: String) -> String {
        guard let value = strings[active]?[key], !value.isEmpty else { return key }
        return value
    }

    func localize(_ key: String, _ args: CVarArg...) -> String {
        String(format: localize(key), locale: locale, arguments: args)
    }

    private let strings: [AppLanguage: [String: String]] = [
        .english: enStrings,
        .german: deStrings,
        .french: frStrings,
        .spanish: esStrings
    ]
}

// MARK: - Translations

private let enStrings: [String: String] = [

    "action.copy": "Copy",
    "action.recheck": "Re-run checks",
    "action.refresh": "Refresh",
    "action.save": "Save",
    "action.share": "Share",
    "action.shareSection": "Share section",
    "compat.editNote": "Note",
    "compat.notePlaceholder": "Add a note…",
    "details.search": "Search",
    "history.range": "Range",
    "history.range.all": "All",
    "history.range.month": "30 days",
    "history.range.today": "Today",
    "history.range.week": "7 days",
    "history.save": "Save to Files…",
    "live.available": "Available",
    "network.chart": "Network rate",
    "processes.name": "Name",
    "processes.sortBy": "Sort by",
    "report.liveSnapshot": "## Live snapshot",
    "report.saveJson": "Save as JSON…",
    "report.saveMarkdown": "Save as Markdown…",
    "settings.haptics": "Haptic feedback",
    "settings.privacy": "All data is processed locally on this device. Nothing is sent anywhere.",
    "status.uptime": "Uptime",
    "mode.normal": "Normal",
    "mode.expert": "Expert",
    "mode.dev": "Dev",

    "app.title": "iOS Info App",

    "tab.status": "Status",
    "tab.details": "Details",
    "tab.processes": "Processes",
    "tab.network": "Network",
    "tab.settings": "Settings",

    "processes.count": "%d processes",
    "processes.restricted": "iOS blocks the process list in the sandbox. Only this app is visible \u{2013} the full list requires a jailbreak.",
    "processes.self": "this app",
    "processes.terminate": "Terminate",
    "processes.terminateConfirm": "Terminate \"%@\" (PID %d)?",
    "processes.terminateFailed": "Could not terminate process.",
    "processes.cpu": "CPU",
    "processes.memory": "RAM",
    "processes.state.running": "running",
    "processes.state.sleeping": "sleeping",
    "processes.state.stopped": "stopped",
    "processes.state.zombie": "zombie",
    "processes.state.uninterruptible": "uninterruptible",
    "processes.state.idle": "idle",
    "processes.state.unknown": "unknown",

    "network.header": "Network",
    "network.received": "Received",
    "network.sent": "Sent",
    "network.download": "Down",
    "network.upload": "Up",
    "network.rate": "Rate",
    "network.total": "Total",
    "network.interfaces": "Interfaces",
    "network.noData": "No traffic data available.",

    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.language.system": "System",
    "settings.appearance": "Appearance",
    "settings.appearance.system": "System",
    "settings.appearance.light": "Light",
    "settings.appearance.dark": "Dark",
    "settings.updateInterval": "Update interval",

    "status.title": "Status",
    "status.updated": "Updated",
    "status.jitChecks": "JIT checks",
    "status.memoryChecks": "Extended Memory checks",
    "status.card.extendedMemory": "Extended Memory",
    "status.battery": "Battery",
    "status.battery.charging": "Charging",
    "status.battery.full": "Full",
    "status.battery.unplugged": "Not charging",
    "status.battery.unknown": "Unknown",
    "status.battery.low": "Battery below 20% \u{2013} JIT sessions may end abruptly when the device sleeps.",

    "recommendation.title": "JIT Recommendation",

    "history.title": "JIT History",
    "history.empty": "No entries yet",
    "history.export": "Export",
    "history.export.csv": "CSV",
    "history.export.json": "JSON",
    "history.clear": "Clear history",
    "history.clearConfirm": "Delete the entire history?",
    "common.cancel": "Cancel",

    "report.shareAccessibility": "Share report",
    "report.title": "JIT Info Report \u{2014} %@",
    "report.on": "ON",
    "report.off": "OFF",
    "report.jitReason": "JIT reason: %@",
    "report.memoryReason": "Extended Memory reason: %@",
    "report.recommendation": "## Recommendation",
    "report.history": "## JIT History",

    "rec.jitActive": "JIT is active \u{2013} nothing else needed.",
    "rec.reason": "Reason: %@",
    "rec.jbGeneral": "Jailbroken: JIT is usually granted automatically (e.g. Dopamine's \u{201C}Allow JIT in Apps\u{201D}). If not, attach debugserver to the app.",
    "rec.v27": "iOS 27: JIT is only possible via StikDebug (3.1.6+, supports A13/A14/M1) with a per-app script \u{2013} only a few apps work (UTM, MeloNX, maciOS, Geode, Manic EMU, ARMSX2, DukeX).",
    "rec.v26": "iOS 26: Use StikDebug (updated for iOS 26) or SideStore 0.6.2 \u{2013} on-device JIT. Only a few apps work on iOS 26.6+.",
    "rec.v184": "iOS 18.4\u{2013}18.7: Use StikDebug or SideStore 0.6.2 \u{2013} on-device JIT enablers (pair once with a PC).",
    "rec.v18": "iOS 18.0\u{2013}18.3: Use StikJIT / StikDebug, SideStore or JITStreamer-EB \u{2013} on-device or network JIT enablers.",
    "rec.v174": "iOS 17.4\u{2013}17.9: Use StikJIT / StikDebug \u{2013} on-device JIT (pair once with a PC, needs LocalDevVPN).",
    "rec.v173": "iOS 17.0.1\u{2013}17.3: Use SideJITServer (PC/Mac) or AltJIT via pymobiledevice3 on macOS.",
    "rec.v170": "iOS 17.0: Install TrollStore (CoreTrust bug) and launch the app with JIT.",
    "rec.v16": "iOS 16.x: Install TrollStore and launch the app with JIT. Alternative: AltJIT via AltServer or SideStore.",
    "rec.v15": "iOS 15.x: Install TrollStore and launch the app with JIT. Alternative: AltJIT via AltServer.",
    "rec.tipGetTaskAllow": "Your sideloaded app must include the get-task-allow entitlement, otherwise JIT tools cannot attach.",
    "rec.xcode": "Universal: Launch the app from Xcode on a Mac (get-task-allow) and attach the debugger \u{2013} enables JIT without a jailbreak.",

    "notif.logChanged": "Status changed",
    "notif.logInitial": "Initial status",

    "section.system": "System",
    "section.cpuRam": "CPU & RAM",
    "section.memory": "Memory",
    "section.storage": "Storage",
    "section.battery": "Battery",
    "section.batteryPower": "Battery & Power",
    "section.screen": "Screen",
    "section.network": "Network",
    "section.locale": "Locale",
    "section.app": "App",
    "section.kernel": "Kernel",
    "section.entitlements": "Entitlements",

    "expl.csopsDebugged": "CS_DEBUGGED is set when the process is or has been debugged \u{2013} the kernel then allows JIT via the debugger.",
    "expl.ptraced": "P_TRACED indicates an active ptrace debugger \u{2013} this allows JIT in the kernel.",
    "expl.allowJit": "The 'com.apple.security.cs.allow-jit' entitlement allows the process JIT mapping (memory RW\u{2192}RX).",
    "expl.dynamicCodesigning": "'dynamic-codesigning' allows code-signing states to be changed at runtime \u{2013} a prerequisite for JIT.",
    "expl.jitEntitled": "Kernel sysctl: '1' means the process is marked as JIT-entitled.",
    "expl.jailbreakHints": "Typical jailbreak/rootful paths. If they exist or system paths are writable, this points to a jailbreak.",
    "expl.increasedMemory": "'com.apple.developer.kernel.increased-memory-limit' raises the process memory limit.",
    "expl.increasedDebug": "'com.apple.developer.kernel.increased-debugging-memory-limit' additionally raises the memory limit for debug calls.",
    "expl.extendedVA": "'com.apple.developer.kernel.extended-virtual-addressing' allows extended virtual addressing (beyond 4 GB).",
    "expl.availableMemory": "Bytes still available until the dirty memory limit is hit. The limit itself \u{2248} this value + the current phys_footprint.",
    "expl.memoryLimit": "Estimated process memory limit = os_proc_available_memory() + phys_footprint. iOS default is roughly half the RAM.",
    "expl.ramShare": "Share of the estimated memory limit relative to the physical RAM. \u{2265} 70 % means a raised limit is active.",
    "expl.extendedVerdict": "YES only if the measured limit is \u{2265} 70 % of RAM. Entitlements alone do not prove a raised limit \u{2013} older devices ignore them.",
    "expl.rlimitAS": "Resource limit for the virtual address size. 'cur' = current, 'max' = hard limit, 'unlimited' = no limit.",
    "expl.rlimitData": "Resource limit for the heap / data segment of the process.",
    "expl.physFootprint": "Physical memory footprint of the process (the reliable value since iOS 13).",
    "expl.resident": "Portion of the process currently in RAM (not swapped out).",
    "expl.virtual": "Virtually reserved address space \u{2013} can be much larger than the RAM.",
    "expl.allowJitShort": "Allows JIT (RW\u{2192}RX) mapping for the process.",
    "expl.increasedMemoryShort": "Raises the process memory limit.",
    "expl.increasedDebugShort": "Raises the memory limit for debug calls.",
    "expl.extendedVAShort": "Allows extended virtual addressing.",
    "expl.getTaskAllow": "Allows debuggers (e.g. Xcode) to attach to this app \u{2013} prerequisite for JIT via debugger.",
    "expl.csopsFlags": "Raw flags from csops(CS_OPS_STATUS): the code-signing attributes of the process, decoded with official names in Dev mode.",

    "settings.mode": "Mode",
    "status.on": "ON",
    "status.off": "OFF",
    "status.live": "Live",
    "live.cpu": "CPU",
    "live.memory": "Memory",
    "live.thermal": "Thermal",
    "live.requires16": "Live charts require iOS 16+.",
    "section.power": "Power",
    "power.thermal": "Thermal state",
    "power.lowPower": "Low power mode",
    "power.appState": "App state",
    "power.thermal.nominal": "nominal",
    "power.thermal.fair": "fair",
    "power.thermal.serious": "serious",
    "power.thermal.critical": "critical",
    "power.state.active": "active",
    "power.state.inactive": "inactive",
    "power.state.background": "background",
    "network.status.unknown": "Unknown",
    "network.status.wifi": "Wi-Fi",
    "network.status.cellular": "Cellular",
    "network.status.ethernet": "Ethernet",
    "network.status.online": "Online",
    "network.status.requiresConnection": "Requires connection",
    "network.status.offline": "Offline",
    "compat.title": "Compatibility",
    "compat.search": "Search apps\u{2026}",
    "compat.ios": "iOS %@",
    "compat.needsJit": "needs JIT",
    "compat.jitUnknown": "JIT requirement unconfirmed",
    "compat.visit": "Visit website",
    "compat.category.emulator": "Emulator",
    "compat.category.tool": "Tool",
    "compat.note.utm": "QEMU-based virtual machines. JIT gives a big speed boost.",
    "compat.note.dolphin": "GameCube/Wii. iOS 26.6+ is not supported.",
    "compat.note.macios": "Runs macOS on Apple Silicon devices.",
    "compat.note.flycast": "Dreamcast. Use the iOS 26 fork on 26+.",
    "compat.note.dukex": "N64. On iOS 27 only on A13/A14/M1.",
    "compat.note.ppsspp": "PSP. Runs without JIT, but much faster with it.",
    "compat.note.sidestore": "SideStore 0.6.2 has built-in on-device JIT (iOS 16 and below or older non-TXM devices).",
    "compat.note.stikdebug": "Latest StikDebug works on iOS 17.4\u{2013}18.x and has a fix for iOS 26/27.",
    "compat.note.trollstore": "TrollStore 14.0b2\u{2013}16.6.1, 16.7RC, 17.0. Launch apps with JIT.",
    "rec.soc.checkra1n": "Your %@ chip is supported by checkra1n (A8\u{2013}A11) \u{2013} semi-tethered jailbreak as an alternative.",
    "rec.soc.stikFixApplies": "Your %@ chip is covered by the StikDebug 3.1.6 fix \u{2013} the on-device JIT script should work.",
    "rec.soc.stikFixNotApplies": "Your %@ chip is NOT covered by the StikDebug fix \u{2013} a per-app script (A15+/M2+) or a PC-based tool is needed.",
    "report.processes": "Processes",
    "report.processesRestricted": "Process list is restricted by iOS \u{2013} only this app is visible.",
    "report.format.markdown": "Markdown",
    "report.format.json": "JSON"
]

private let deStrings: [String: String] = [

    "action.copy": "Kopieren",
    "action.recheck": "Checks erneut ausführen",
    "action.refresh": "Aktualisieren",
    "action.save": "Speichern",
    "action.share": "Teilen",
    "action.shareSection": "Abschnitt teilen",
    "compat.editNote": "Notiz",
    "compat.notePlaceholder": "Notiz hinzufügen…",
    "details.search": "Suchen",
    "history.range": "Zeitraum",
    "history.range.all": "Alle",
    "history.range.month": "30 Tage",
    "history.range.today": "Heute",
    "history.range.week": "7 Tage",
    "history.save": "In Dateien sichern…",
    "live.available": "Verfügbar",
    "network.chart": "Netzwerkrate",
    "processes.name": "Name",
    "processes.sortBy": "Sortieren nach",
    "report.liveSnapshot": "## Live-Schnappschuss",
    "report.saveJson": "Als JSON speichern…",
    "report.saveMarkdown": "Als Markdown speichern…",
    "settings.haptics": "Haptisches Feedback",
    "settings.privacy": "Alle Daten werden lokal auf diesem Gerät verarbeitet. Es wird nichts gesendet.",
    "status.uptime": "Laufzeit",
    "mode.normal": "Normal",
    "mode.expert": "Experte",
    "mode.dev": "Dev",

    "app.title": "iOS Info App",

    "tab.status": "Status",
    "tab.details": "Details",
    "tab.processes": "Prozesse",
    "tab.network": "Netzwerk",
    "tab.settings": "Einstellungen",

    "processes.count": "%d Prozesse",
    "processes.restricted": "iOS blockiert die Prozessliste in der Sandbox. Nur diese App ist sichtbar \u{2013} die vollst\u{00E4}ndige Liste erfordert einen Jailbreak.",
    "processes.self": "diese App",
    "processes.terminate": "Beenden",
    "processes.terminateConfirm": "\u{201E}%@\u{201C} (PID %d) beenden?",
    "processes.terminateFailed": "Prozess konnte nicht beendet werden.",
    "processes.cpu": "CPU",
    "processes.memory": "RAM",
    "processes.state.running": "l\u{00E4}uft",
    "processes.state.sleeping": "schl\u{00E4}ft",
    "processes.state.stopped": "gestoppt",
    "processes.state.zombie": "Zombie",
    "processes.state.uninterruptible": "unterbrechungsfrei",
    "processes.state.idle": "im Leerlauf",
    "processes.state.unknown": "unbekannt",

    "network.header": "Netzwerk",
    "network.received": "Empfangen",
    "network.sent": "Gesendet",
    "network.download": "Down",
    "network.upload": "Up",
    "network.rate": "Rate",
    "network.total": "Gesamt",
    "network.interfaces": "Schnittstellen",
    "network.noData": "Keine Netzwerkdaten verf\u{00FC}gbar.",

    "settings.title": "Einstellungen",
    "settings.language": "Sprache",
    "settings.language.system": "System",
    "settings.appearance": "Darstellung",
    "settings.appearance.system": "System",
    "settings.appearance.light": "Hell",
    "settings.appearance.dark": "Dunkel",
    "settings.updateInterval": "Update-Intervall",

    "status.title": "Status",
    "status.updated": "Aktualisiert",
    "status.jitChecks": "JIT-Checks",
    "status.memoryChecks": "Extended-Memory-Checks",
    "status.card.extendedMemory": "Erweiterter Speicher",
    "status.battery": "Akku",
    "status.battery.charging": "L\u{00E4}dt",
    "status.battery.full": "Voll",
    "status.battery.unplugged": "Nicht am Ladeger\u{00E4}t",
    "status.battery.unknown": "Unbekannt",
    "status.battery.low": "Akku unter 20 % \u{2013} JIT-Sitzungen k\u{00F6}nnen beim Schlafenlegen des Ger\u{00E4}ts abrupt enden.",

    "recommendation.title": "Empfehlung f\u{00FC}r JIT",

    "history.title": "JIT-Verlauf",
    "history.empty": "Noch keine Eintr\u{00E4}ge",
    "history.export": "Exportieren",
    "history.export.csv": "CSV",
    "history.export.json": "JSON",
    "history.clear": "Verlauf l\u{00F6}schen",
    "history.clearConfirm": "Gesamten Verlauf l\u{00F6}schen?",
    "common.cancel": "Abbrechen",

    "report.shareAccessibility": "Report teilen",
    "report.title": "JIT Info Report \u{2013} %@",
    "report.on": "AN",
    "report.off": "AUS",
    "report.jitReason": "JIT-Grund: %@",
    "report.memoryReason": "Extended-Memory-Grund: %@",
    "report.recommendation": "## Empfehlung",
    "report.history": "## JIT-Verlauf",

    "rec.jitActive": "JIT ist aktiv \u{2013} nichts weiter n\u{00F6}tig.",
    "rec.reason": "Grund: %@",
    "rec.jbGeneral": "Gejailbreakt: JIT wird meist automatisch erteilt (z. B. Dopamines \u{201E}Allow JIT in Apps\u{201C}). Falls nicht, debugserver an die App anh\u{00E4}ngen.",
    "rec.v27": "iOS 27: JIT ist nur \u{00FC}ber StikDebug (3.1.6+, unterst\u{00FC}tzt A13/A14/M1) mit einem App-Skript m\u{00F6}glich \u{2013} nur wenige Apps funktionieren (UTM, MeloNX, maciOS, Geode, Manic EMU, ARMSX2, DukeX).",
    "rec.v26": "iOS 26: StikDebug (f\u{00FC}r iOS 26 aktualisiert) oder SideStore 0.6.2 nutzen \u{2013} JIT direkt am Ger\u{00E4}t. Nur wenige Apps funktionieren auf iOS 26.6+.",
    "rec.v184": "iOS 18.4\u{2013}18.7: StikDebug oder SideStore 0.6.2 nutzen \u{2013} On-Device-JIT (einmal mit PC koppeln).",
    "rec.v18": "iOS 18.0\u{2013}18.3: StikJIT / StikDebug, SideStore oder JITStreamer-EB nutzen \u{2013} JIT direkt am Ger\u{00E4}t oder \u{00FC}ber Netzwerk.",
    "rec.v174": "iOS 17.4\u{2013}17.9: StikJIT / StikDebug nutzen \u{2013} On-Device-JIT (einmal mit PC koppeln, ben\u{00F6}tigt LocalDevVPN).",
    "rec.v173": "iOS 17.0.1\u{2013}17.3: SideJITServer (PC/Mac) oder AltJIT per pymobiledevice3 auf macOS verwenden.",
    "rec.v170": "iOS 17.0: TrollStore installieren (CoreTrust-Bug) und die App mit JIT starten.",
    "rec.v16": "iOS 16.x: TrollStore installieren und die App mit JIT starten. Alternative: AltJIT \u{00FC}ber AltServer oder SideStore.",
    "rec.v15": "iOS 15.x: TrollStore installieren und die App mit JIT starten. Alternative: AltJIT \u{00FC}ber AltServer.",
    "rec.tipGetTaskAllow": "Die sideloaded App muss die get-task-allow-Berechtigung enthalten, sonst k\u{00F6}nnen JIT-Tools nicht andocken.",
    "rec.xcode": "Universell: App am Mac aus Xcode starten (get-task-allow) und Debugger anh\u{00E4}ngen \u{2013} aktiviert JIT ohne Jailbreak.",

    "notif.logChanged": "Status gewechselt",
    "notif.logInitial": "Initialstatus",

    "section.system": "System",
    "section.cpuRam": "CPU & RAM",
    "section.memory": "Speicher",
    "section.storage": "Speicherplatz",
    "section.battery": "Akku",
    "section.batteryPower": "Akku & Energie",
    "section.screen": "Display",
    "section.network": "Netzwerk",
    "section.locale": "Region",
    "section.app": "App",
    "section.kernel": "Kernel",
    "section.entitlements": "Entitlements",

    "expl.csopsDebugged": "CS_DEBUGGED ist gesetzt, wenn der Prozess gerade oder fr\u{00FC}her debuggt wurde \u{2013} der Kernel erlaubt dann JIT \u{00FC}ber den Debugger.",
    "expl.ptraced": "P_TRACED zeigt einen aktiven ptrace-Debugger an \u{2013} dadurch ist JIT im Kernel erlaubt.",
    "expl.allowJit": "Das Entitlement 'com.apple.security.cs.allow-jit' erlaubt dem Prozess JIT-Mapping (Speicher RW\u{2192}RX).",
    "expl.dynamicCodesigning": "'dynamic-codesigning' erlaubt zur Laufzeit ge\u{00E4}nderte Code-Signatur-Zust\u{00E4}nde \u{2013} Voraussetzung f\u{00FC}r JIT.",
    "expl.jitEntitled": "Kernel-Sysctl: '1' bedeutet, der Prozess ist als JIT-berechtigt markiert.",
    "expl.jailbreakHints": "Typische Jailbreak-/Rootful-Pfade. Existieren sie bzw. sind Systempfade beschreibbar, deutet das auf einen Jailbreak hin.",
    "expl.increasedMemory": "'com.apple.developer.kernel.increased-memory-limit' hebt das Speicherlimit des Prozesses an.",
    "expl.increasedDebug": "'com.apple.developer.kernel.increased-debugging-memory-limit' erh\u{00F6}ht das Speicherlimit zus\u{00E4}tzlich f\u{00FC}r Debug-Aufrufe.",
    "expl.extendedVA": "'com.apple.developer.kernel.extended-virtual-addressing' erlaubt erweiterte virtuelle Adressierung (\u{00FC}ber 4 GB hinaus).",
    "expl.availableMemory": "Noch verf\u{00FC}gbare Bytes, bis die Dirty-Memory-Grenze erreicht ist. Das Limit selbst \u{2248} dieser Wert + aktueller phys_footprint.",
    "expl.memoryLimit": "Gesch\u{00E4}tzte Speichergrenze des Prozesses = os_proc_available_memory() + phys_footprint. iOS-Standard ist etwa die H\u{00E4}lfte des RAMs.",
    "expl.ramShare": "Anteil der gesch\u{00E4}tzten Speichergrenze am physikalischen RAM. \u{2265} 70 % bedeutet ein angehobenes Limit.",
    "expl.extendedVerdict": "YES nur, wenn das gemessene Limit \u{2265} 70 % des RAMs betr\u{00E4}gt. Entitlements allein beweisen kein angehobenes Limit \u{2013} \u{00E4}ltere Ger\u{00E4}te ignorieren sie.",
    "expl.rlimitAS": "Resource-Limit f\u{00FC}r die virtuelle Adressgr\u{00F6}\u{00DF}e. 'cur' = aktuell, 'max' = hartes Limit, 'unlimited' = unbegrenzt.",
    "expl.rlimitData": "Resource-Limit f\u{00FC}r Heap bzw. Daten-Segment des Prozesses.",
    "expl.physFootprint": "Physischer Speicherfu\u{00DF}abdruck des Prozesses (seit iOS 13 der zuverl\u{00E4}ssige Wert).",
    "expl.resident": "Anteil des Prozesses, der gerade im RAM liegt (nicht ausgelagert).",
    "expl.virtual": "Virtuell reservierte Adressmenge \u{2013} kann deutlich gr\u{00F6}\u{00DF}er als der RAM sein.",
    "expl.allowJitShort": "Erlaubt JIT (RW\u{2192}RX)-Mapping f\u{00FC}r den Prozess.",
    "expl.increasedMemoryShort": "Hebt das Speicherlimit des Prozesses an.",
    "expl.increasedDebugShort": "Erh\u{00F6}ht das Speicherlimit f\u{00FC}r Debug-Aufrufe.",
    "expl.extendedVAShort": "Erlaubt erweiterte virtuelle Adressierung.",
    "expl.getTaskAllow": "Erlaubt Debuggern (z. B. Xcode), sich an diese App zu h\u{00E4}ngen \u{2013} Voraussetzung f\u{00FC}r JIT per Debugger.",
    "expl.csopsFlags": "Roh-Flags aus csops(CS_OPS_STATUS): die Code-Signing-Attribute des Prozesses, im Dev-Modus als offizielle Namen decodiert.",

    "settings.mode": "Modus",
    "status.on": "AN",
    "status.off": "AUS",
    "status.live": "Live",
    "live.cpu": "CPU",
    "live.memory": "Speicher",
    "live.thermal": "Thermik",
    "live.requires16": "Live-Diagramme erfordern iOS 16+.",
    "section.power": "Energie",
    "power.thermal": "Thermischer Zustand",
    "power.lowPower": "Energiesparmodus",
    "power.appState": "App-Zustand",
    "power.thermal.nominal": "normal",
    "power.thermal.fair": "erh\u{00F6}ht",
    "power.thermal.serious": "kritisch",
    "power.thermal.critical": "dringend kritisch",
    "power.state.active": "aktiv",
    "power.state.inactive": "inaktiv",
    "power.state.background": "im Hintergrund",
    "network.status.unknown": "Unbekannt",
    "network.status.wifi": "WLAN",
    "network.status.cellular": "Mobilfunk",
    "network.status.ethernet": "Ethernet",
    "network.status.online": "Online",
    "network.status.requiresConnection": "Verbindung erforderlich",
    "network.status.offline": "Offline",
    "compat.title": "Kompatibilit\u{00E4}t",
    "compat.search": "Apps suchen\u{2026}",
    "compat.ios": "iOS %@",
    "compat.needsJit": "braucht JIT",
    "compat.jitUnknown": "JIT-Bedarf unbesta\u{00E4}tigt",
    "compat.visit": "Website besuchen",
    "compat.category.emulator": "Emulator",
    "compat.category.tool": "Werkzeug",
    "compat.note.utm": "QEMU-basierte virtuelle Maschinen. JIT bringt gro\u{00DF}en Geschwindigkeitsschub.",
    "compat.note.dolphin": "GameCube/Wii. iOS 26.6+ wird nicht unterst\u{00FC}tzt.",
    "compat.note.macios": "F\u{00FC}hrt macOS auf Apple-Silicon-Ger\u{00E4}ten aus.",
    "compat.note.flycast": "Dreamcast. Auf 26+ den iOS-26-Fork verwenden.",
    "compat.note.dukex": "N64. Auf iOS 27 nur auf A13/A14/M1.",
    "compat.note.ppsspp": "PSP. L\u{00E4}uft ohne JIT, aber deutlich schneller damit.",
    "compat.note.sidestore": "SideStore 0.6.2 hat eingebautes On-Device-JIT (iOS 16 und darunter oder \u{00E4}ltere Nicht-TXM-Ger\u{00E4}te).",
    "compat.note.stikdebug": "Aktuelles StikDebug funktioniert auf iOS 17.4\u{2013}18.x und hat einen Fix f\u{00FC}r iOS 26/27.",
    "compat.note.trollstore": "TrollStore 14.0b2\u{2013}16.6.1, 16.7RC, 17.0. Apps mit JIT starten.",
    "rec.soc.checkra1n": "Dein %@-Chip wird von checkra1n (A8\u{2013}A11) unterst\u{00FC}tzt \u{2013} Semi-Tethered-Jailbreak als Alternative.",
    "rec.soc.stikFixApplies": "Dein %@-Chip wird vom StikDebug-3.1.6-Fix abgedeckt \u{2013} das On-Device-JIT-Skript sollte funktionieren.",
    "rec.soc.stikFixNotApplies": "Dein %@-Chip wird vom StikDebug-Fix NICHT abgedeckt \u{2013} ein App-Skript (A15+/M2+) oder ein PC-Tool ist n\u{00F6}tig.",
    "report.processes": "Prozesse",
    "report.processesRestricted": "Die Prozessliste wird von iOS eingeschr\u{00E4}nkt \u{2013} nur diese App ist sichtbar.",
    "report.format.markdown": "Markdown",
    "report.format.json": "JSON",

    "Device name": "Ger\u{00E4}tename",
    "Build": "Build",
    "Display name": "Anzeigename",
    "Executable architecture": "Architektur der ausführbaren Datei",
    "Product type": "Produkttyp",
    "Model identifier": "Modellkennung",
    "Marketing name": "Marketingname",
    "SoC / board": "SoC / Board",
    "iOS version": "iOS-Version",
    "Kernel release": "Kernel-Release",
    "Kernel build": "Kernel-Build",
    "Uptime": "Laufzeit",
    "Jailbroken hints": "Jailbreak-Hinweise",
    "Jailbreak hints": "Jailbreak-Hinweise",
    "CPU count": "CPU-Anzahl",
    "Physical cores": "Physische Kerne",
    "CPU frequency": "CPU-Takt",
    "Architecture": "Architektur",
    "Physical RAM": "Physischer RAM",
    "Free pages": "Freie Seiten",
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Wired": "Wired",
    "Compressed": "Komprimiert",
    "App phys_footprint": "App phys_footprint",
    "App resident": "App resident",
    "App virtual": "App virtual",
    "RLIMIT_AS cur/max": "RLIMIT_AS aktuell/max",
    "RLIMIT_DATA cur/max": "RLIMIT_DATA aktuell/max",
    "Disk capacity": "Speicherkapazit\u{00E4}t",
    "Disk free": "Speicher frei",
    "Storage": "Speicher",
    "Level": "Ladestand",
    "State": "Zustand",
    "Bounds": "Abmessungen",
    "Scale": "Skalierung",
    "Native": "Nativ",
    "Max FPS": "Max. FPS",
    "Frame duration (min)": "Bilddauer (min)",
    "Brightness": "Helligkeit",
    "True Tone": "True Tone",
    "Status": "Status",
    "Locale": "Region",
    "Region": "Region",
    "Language": "Sprache",
    "24-hour": "24-Stunden",
    "Time zone": "Zeitzone",
    "Bundle name": "Bundle-Name",
    "Bundle identifier": "Bundle-ID",
    "Version": "Version",
    "Process ID": "Prozess-ID",
    "Parent PID": "\u{00DC}bergeordnete PID",
    "Executable path": "Pfad der ausf\u{00FC}hrbaren Datei",
    "Entitlement allow-jit": "Berechtigung allow-jit",
    "Entitlement increased-memory-limit": "Berechtigung increased-memory-limit",
    "Entitlement increased-debugging-memory-limit": "Berechtigung increased-debugging-memory-limit",
    "Entitlement extended-virtual-addressing": "Berechtigung extended-virtual-addressing",
    "Entitlement dynamic-codesigning": "Berechtigung dynamic-codesigning",
    "Memory limit (est.)": "Speicherlimit (gesch\u{00E4}tzt)",
    "Share of physical RAM": "Anteil am physischen RAM",
    "Extended memory verdict": "Extended-Memory-Urteil",
    "phys_footprint": "phys_footprint",
    "Resident size": "Residente Gr\u{00F6}\u{00DF}e",
    "Virtual size": "Virtuelle Gr\u{00F6}\u{00DF}e",
    "Entitlements": "Entitlements"
]

private let frStrings: [String: String] = [
    "24-hour": "24 heures",
    "Active": "Actif",
    "App phys_footprint": "Empreinte physique de l'app",
    "App resident": "Résident de l'app",
    "App virtual": "Virtuel de l'app",
    "Architecture": "Architecture",
    "Bounds": "Dimensions",
    "Brightness": "Luminosité",
    "Build": "Build",
    "Bundle identifier": "Identifiant du bundle",
    "Bundle name": "Nom du bundle",
    "CPU count": "Nombre de CPU",
    "CPU frequency": "Fréquence CPU",
    "Compressed": "Compressé",
    "Device name": "Nom de l'appareil",
    "Disk capacity": "Capacité du disque",
    "Disk free": "Espace libre du disque",
    "Display name": "Nom d'affichage",
    "Entitlement allow-jit": "Entitlement allow-jit",
    "Entitlement dynamic-codesigning": "Entitlement dynamic-codesigning",
    "Entitlement extended-virtual-addressing": "Entitlement extended-virtual-addressing",
    "Entitlement increased-debugging-memory-limit": "Entitlement increased-debugging-memory-limit",
    "Entitlement increased-memory-limit": "Entitlement increased-memory-limit",
    "Entitlements": "Entitlements",
    "Executable architecture": "Architecture de l'exécutable",
    "Executable path": "Chemin de l'exécutable",
    "Extended memory verdict": "Verdict mémoire étendue",
    "Frame duration (min)": "Durée d'image (min)",
    "Free pages": "Pages libres",
    "Inactive": "Inactif",
    "Jailbreak hints": "Indices de jailbreak",
    "Jailbroken hints": "Indices de jailbreak",
    "Kernel build": "Build du noyau",
    "Kernel release": "Version du noyau",
    "Language": "Langue",
    "Level": "Niveau",
    "Locale": "Locale",
    "Marketing name": "Nom commercial",
    "Max FPS": "FPS max",
    "Memory limit (est.)": "Limite mémoire (est.)",
    "Model identifier": "Identifiant du modèle",
    "Native": "Natif",
    "Parent PID": "PID parent",
    "Physical RAM": "RAM physique",
    "Physical cores": "Cœurs physiques",
    "Process ID": "ID de processus",
    "Product type": "Type de produit",
    "RLIMIT_AS cur/max": "RLIMIT_AS actuel/max",
    "RLIMIT_DATA cur/max": "RLIMIT_DATA actuel/max",
    "Region": "Région",
    "Resident size": "Taille résidente",
    "Scale": "Échelle",
    "Share of physical RAM": "Part de la RAM physique",
    "SoC / board": "SoC / carte",
    "State": "État",
    "Status": "Statut",
    "Storage": "Stockage",
    "Time zone": "Fuseau horaire",
    "True Tone": "True Tone",
    "Uptime": "Temps de fonctionnement",
    "Version": "Version",
    "Virtual size": "Taille virtuelle",
    "Wired": "Câblé",
    "action.copy": "Copier",
    "action.recheck": "Relancer les vérifications",
    "action.refresh": "Actualiser",
    "action.save": "Enregistrer",
    "action.share": "Partager",
    "action.shareSection": "Partager la section",
    "app.title": "iOS Info App",
    "common.cancel": "Annuler",
    "compat.category.emulator": "Émulateur",
    "compat.category.tool": "Outil",
    "compat.editNote": "Note",
    "compat.ios": "iOS %@",
    "compat.jitUnknown": "Exigence JIT non confirmée",
    "compat.needsJit": "nécessite JIT",
    "compat.note.dolphin": "GameCube/Wii. iOS 26.6+ n'est pas pris en charge.",
    "compat.note.dukex": "N64. Sur iOS 27 uniquement sur A13/A14/M1.",
    "compat.note.flycast": "Dreamcast. Utilisez le fork iOS 26 sur 26+.",
    "compat.note.macios": "Exécute macOS sur les appareils Apple Silicon.",
    "compat.note.ppsspp": "PSP. Fonctionne sans JIT, mais beaucoup plus rapide avec.",
    "compat.note.sidestore": "SideStore 0.6.2 a un JIT intégré sur l'appareil (iOS 16 et inférieur ou anciens appareils non-TXM).",
    "compat.note.stikdebug": "Le dernier StikDebug fonctionne sur iOS 17.4–18.x et a un correctif pour iOS 26/27.",
    "compat.note.trollstore": "TrollStore 14.0b2–16.6.1, 16.7RC, 17.0. Lancez des apps avec JIT.",
    "compat.note.utm": "Machines virtuelles basées sur QEMU. JIT donne un gros coup de boost en vitesse.",
    "compat.notePlaceholder": "Ajouter une note…",
    "compat.search": "Rechercher des apps…",
    "compat.title": "Compatibilité",
    "compat.visit": "Visiter le site web",
    "details.search": "Rechercher",
    "expl.allowJit": "L'entitlement 'com.apple.security.cs.allow-jit' autorise le mapping JIT du processus (mémoire RW→RX).",
    "expl.allowJitShort": "Autorise le mapping JIT (RW→RX) pour le processus.",
    "expl.availableMemory": "Octets encore disponibles jusqu'à la limite de mémoire sale. La limite ≈ cette valeur + phys_footprint actuel.",
    "expl.csopsDebugged": "CS_DEBUGGED est défini lorsque le processus est (ou a été) débogué – le noyau autorise alors JIT via le débogueur.",
    "expl.csopsFlags": "Drapeaux bruts de csops(CS_OPS_STATUS) : les attributs de signature de code du processus, décodés avec les noms officiels en mode Dev.",
    "expl.dynamicCodesigning": "'dynamic-codesigning' permet de modifier les états de signature de code à l'exécution – une condition préalable pour JIT.",
    "expl.extendedVA": "'com.apple.developer.kernel.extended-virtual-addressing' autorise l'adressage virtuel étendu (au-delà de 4 Go).",
    "expl.extendedVAShort": "Autorise l'adressage virtuel étendu.",
    "expl.extendedVerdict": "YES uniquement si la limite mesurée est ≥ 70 % de la RAM. Les entitlements seuls ne prouvent pas une limite relevée – les anciens appareils les ignorent.",
    "expl.getTaskAllow": "Autorise les débogueurs (p. ex. Xcode) à s'attacher à cette app – condition préalable pour JIT via débogueur.",
    "expl.increasedDebug": "'com.apple.developer.kernel.increased-debugging-memory-limit' relève en plus la limite mémoire pour les appels de débogage.",
    "expl.increasedDebugShort": "Relève la limite mémoire pour les appels de débogage.",
    "expl.increasedMemory": "'com.apple.developer.kernel.increased-memory-limit' relève la limite mémoire du processus.",
    "expl.increasedMemoryShort": "Relève la limite mémoire du processus.",
    "expl.jailbreakHints": "Chemins typiques de jailbreak/rootful. S'ils existent ou si les chemins système sont inscriptibles, cela indique un jailbreak.",
    "expl.jitEntitled": "Sysctl noyau : '1' signifie que le processus est marqué comme autorisé pour JIT.",
    "expl.memoryLimit": "Limite mémoire estimée du processus = os_proc_available_memory() + phys_footprint. La valeur par défaut d'iOS est environ la moitié de la RAM.",
    "expl.physFootprint": "Empreinte mémoire physique du processus (la valeur fiable depuis iOS 13).",
    "expl.ptraced": "P_TRACED indique un débogueur ptrace actif – cela autorise JIT dans le noyau.",
    "expl.ramShare": "Part de la limite mémoire estimée par rapport à la RAM physique. ≥ 70 % signifie une limite relevée.",
    "expl.resident": "Partie du processus actuellement en RAM (non échangée).",
    "expl.rlimitAS": "Limite de ressources pour la taille d'adressage virtuel. 'cur' = actuelle, 'max' = limite dure, 'unlimited' = sans limite.",
    "expl.rlimitData": "Limite de ressources pour le tas / segment de données du processus.",
    "expl.virtual": "Espace d'adressage réservé virtuellement – peut être bien plus grand que la RAM.",
    "history.clear": "Effacer l'historique",
    "history.clearConfirm": "Supprimer tout l'historique ?",
    "history.empty": "Aucune entrée pour l'instant",
    "history.export": "Exporter",
    "history.export.csv": "CSV",
    "history.export.json": "JSON",
    "history.range": "Période",
    "history.range.all": "Tout",
    "history.range.month": "30 jours",
    "history.range.today": "Aujourd'hui",
    "history.range.week": "7 jours",
    "history.save": "Enregistrer dans Fichiers…",
    "history.title": "Historique JIT",
    "iOS version": "Version d'iOS",
    "live.available": "Disponible",
    "live.cpu": "CPU",
    "live.memory": "Mémoire",
    "live.requires16": "Les graphiques en direct nécessitent iOS 16+.",
    "live.thermal": "Thermique",
    "mode.dev": "Dev",
    "mode.expert": "Expert",
    "mode.normal": "Normal",
    "network.chart": "Débit réseau",
    "network.download": "Desc.",
    "network.header": "Réseau",
    "network.interfaces": "Interfaces",
    "network.noData": "Aucune donnée de trafic disponible.",
    "network.rate": "Débit",
    "network.received": "Reçu",
    "network.sent": "Envoyé",
    "network.status.cellular": "Cellulaire",
    "network.status.ethernet": "Ethernet",
    "network.status.offline": "Hors ligne",
    "network.status.online": "En ligne",
    "network.status.requiresConnection": "Nécessite une connexion",
    "network.status.unknown": "Inconnu",
    "network.status.wifi": "Wi-Fi",
    "network.total": "Total",
    "network.upload": "Mont.",
    "notif.logChanged": "Statut modifié",
    "notif.logInitial": "Statut initial",
    "phys_footprint": "phys_footprint",
    "power.appState": "État de l'app",
    "power.lowPower": "Mode économie d'énergie",
    "power.state.active": "active",
    "power.state.background": "en arrière-plan",
    "power.state.inactive": "inactive",
    "power.thermal": "État thermique",
    "power.thermal.critical": "critique",
    "power.thermal.fair": "moyen",
    "power.thermal.nominal": "nominal",
    "power.thermal.serious": "sérieux",
    "processes.count": "%d processus",
    "processes.cpu": "CPU",
    "processes.memory": "RAM",
    "processes.name": "Nom",
    "processes.restricted": "iOS bloque la liste des processus dans la sandbox. Seule cette app est visible – la liste complète nécessite un jailbreak.",
    "processes.self": "cette app",
    "processes.sortBy": "Trier par",
    "processes.state.idle": "inactif",
    "processes.state.running": "en cours",
    "processes.state.sleeping": "en veille",
    "processes.state.stopped": "arrêté",
    "processes.state.uninterruptible": "ininterrompu",
    "processes.state.unknown": "inconnu",
    "processes.state.zombie": "zombie",
    "processes.terminate": "Terminer",
    "processes.terminateConfirm": "Terminer « %@ » (PID %d) ?",
    "processes.terminateFailed": "Impossible de terminer le processus.",
    "rec.jbGeneral": "Jailbreak : JIT est généralement accordé automatiquement (p. ex. « Allow JIT in Apps » de Dopamine). Sinon, attachez debugserver à l'app.",
    "rec.jitActive": "JIT est actif – rien d'autre à faire.",
    "rec.reason": "Raison : %@",
    "rec.soc.checkra1n": "Votre puce %@ est prise en charge par checkra1n (A8–A11) – jailbreak semi-tethered en alternative.",
    "rec.soc.stikFixApplies": "Votre puce %@ est couverte par le correctif StikDebug 3.1.6 – le script JIT sur l'appareil devrait fonctionner.",
    "rec.soc.stikFixNotApplies": "Votre puce %@ n'est PAS couverte par le correctif StikDebug – un script par app (A15+/M2+) ou un outil PC est nécessaire.",
    "rec.tipGetTaskAllow": "Votre app sideloadée doit inclure l'entitlement get-task-allow, sinon les outils JIT ne peuvent pas s'y attacher.",
    "rec.v15": "iOS 15.x : installez TrollStore et lancez l'app avec JIT. Alternative : AltJIT via AltServer.",
    "rec.v16": "iOS 16.x : installez TrollStore et lancez l'app avec JIT. Alternative : AltJIT via AltServer ou SideStore.",
    "rec.v170": "iOS 17.0 : installez TrollStore (bug CoreTrust) et lancez l'app avec JIT.",
    "rec.v173": "iOS 17.0.1–17.3 : utilisez SideJITServer (PC/Mac) ou AltJIT via pymobiledevice3 sur macOS.",
    "rec.v174": "iOS 17.4–17.9 : utilisez StikJIT / StikDebug – JIT sur l'appareil (appairage unique avec un PC, nécessite LocalDevVPN).",
    "rec.v18": "iOS 18.0–18.3 : utilisez StikJIT / StikDebug, SideStore ou JITStreamer-EB – JIT sur l'appareil ou via le réseau.",
    "rec.v184": "iOS 18.4–18.7 : utilisez StikDebug ou SideStore 0.6.2 – activateurs JIT sur l'appareil (appairage unique avec un PC).",
    "rec.v26": "iOS 26 : utilisez StikDebug (mis à jour pour iOS 26) ou SideStore 0.6.2 – JIT sur l'appareil. Seules quelques apps fonctionnent sur iOS 26.6+.",
    "rec.v27": "iOS 27 : JIT n'est possible que via StikDebug (3.1.6+, prend en charge A13/A14/M1) avec un script par app – seules quelques apps fonctionnent (UTM, MeloNX, maciOS, Geode, Manic EMU, ARMSX2, DukeX).",
    "rec.xcode": "Universel : lancez l'app depuis Xcode sur un Mac (get-task-allow) et attachez le débogueur – active JIT sans jailbreak.",
    "recommendation.title": "Recommandation JIT",
    "report.format.json": "JSON",
    "report.format.markdown": "Markdown",
    "report.history": "## Historique JIT",
    "report.jitReason": "Raison JIT : %@",
    "report.liveSnapshot": "## Aperçu en direct",
    "report.memoryReason": "Raison mémoire étendue : %@",
    "report.off": "OFF",
    "report.on": "ON",
    "report.processes": "Processus",
    "report.processesRestricted": "La liste des processus est restreinte par iOS – seule cette app est visible.",
    "report.recommendation": "## Recommandation",
    "report.saveJson": "Enregistrer en JSON…",
    "report.saveMarkdown": "Enregistrer en Markdown…",
    "report.shareAccessibility": "Partager le rapport",
    "report.title": "Rapport JIT Info – %@",
    "section.app": "App",
    "section.battery": "Batterie",
    "section.batteryPower": "Batterie & énergie",
    "section.cpuRam": "CPU & RAM",
    "section.entitlements": "Entitlements",
    "section.kernel": "Noyau",
    "section.locale": "Locale",
    "section.memory": "Mémoire",
    "section.network": "Réseau",
    "section.power": "Énergie",
    "section.screen": "Écran",
    "section.storage": "Stockage",
    "section.system": "Système",
    "settings.appearance": "Apparence",
    "settings.appearance.dark": "Sombre",
    "settings.appearance.light": "Clair",
    "settings.appearance.system": "Système",
    "settings.haptics": "Retour haptique",
    "settings.language": "Langue",
    "settings.language.system": "Système",
    "settings.mode": "Mode",
    "settings.privacy": "Toutes les données sont traitées localement sur cet appareil. Rien n'est envoyé.",
    "settings.title": "Réglages",
    "settings.updateInterval": "Intervalle de mise à jour",
    "status.battery": "Batterie",
    "status.battery.charging": "Charge en cours",
    "status.battery.full": "Pleine",
    "status.battery.low": "Batterie sous 20 % – les sessions JIT peuvent s'arrêter brusquement quand l'appareil passe en veille.",
    "status.battery.unknown": "Inconnu",
    "status.battery.unplugged": "Pas en charge",
    "status.card.extendedMemory": "Mémoire étendue",
    "status.jitChecks": "Contrôles JIT",
    "status.live": "Live",
    "status.memoryChecks": "Contrôles mémoire étendue",
    "status.off": "OFF",
    "status.on": "ON",
    "status.title": "Statut",
    "status.updated": "Mis à jour",
    "status.uptime": "Temps de fonctionnement",
    "tab.details": "Détails",
    "tab.network": "Réseau",
    "tab.processes": "Processus",
    "tab.settings": "Réglages",
    "tab.status": "Statut",
]

private let esStrings: [String: String] = [
    "24-hour": "24 horas",
    "Active": "Activo",
    "App phys_footprint": "phys_footprint de la app",
    "App resident": "Residente de la app",
    "App virtual": "Virtual de la app",
    "Architecture": "Arquitectura",
    "Bounds": "Dimensiones",
    "Brightness": "Brillo",
    "Build": "Build",
    "Bundle identifier": "Identificador del bundle",
    "Bundle name": "Nombre del bundle",
    "CPU count": "Número de CPU",
    "CPU frequency": "Frecuencia de CPU",
    "Compressed": "Comprimido",
    "Device name": "Nombre del dispositivo",
    "Disk capacity": "Capacidad del disco",
    "Disk free": "Disco libre",
    "Display name": "Nombre para mostrar",
    "Entitlement allow-jit": "Entitlement allow-jit",
    "Entitlement dynamic-codesigning": "Entitlement dynamic-codesigning",
    "Entitlement extended-virtual-addressing": "Entitlement extended-virtual-addressing",
    "Entitlement increased-debugging-memory-limit": "Entitlement increased-debugging-memory-limit",
    "Entitlement increased-memory-limit": "Entitlement increased-memory-limit",
    "Entitlements": "Entitlements",
    "Executable architecture": "Arquitectura del ejecutable",
    "Executable path": "Ruta del ejecutable",
    "Extended memory verdict": "Veredicto de memoria extendida",
    "Frame duration (min)": "Duración de fotograma (mín)",
    "Free pages": "Páginas libres",
    "Inactive": "Inactivo",
    "Jailbreak hints": "Indicios de jailbreak",
    "Jailbroken hints": "Indicios de jailbreak",
    "Kernel build": "Build del núcleo",
    "Kernel release": "Versión del núcleo",
    "Language": "Idioma",
    "Level": "Nivel",
    "Locale": "Locale",
    "Marketing name": "Nombre comercial",
    "Max FPS": "FPS máx",
    "Memory limit (est.)": "Límite de memoria (est.)",
    "Model identifier": "Identificador del modelo",
    "Native": "Nativo",
    "Parent PID": "PID padre",
    "Physical RAM": "RAM física",
    "Physical cores": "Núcleos físicos",
    "Process ID": "ID del proceso",
    "Product type": "Tipo de producto",
    "RLIMIT_AS cur/max": "RLIMIT_AS actual/máx",
    "RLIMIT_DATA cur/max": "RLIMIT_DATA actual/máx",
    "Region": "Región",
    "Resident size": "Tamaño residente",
    "Scale": "Escala",
    "Share of physical RAM": "Proporción de la RAM física",
    "SoC / board": "SoC / placa",
    "State": "Estado",
    "Status": "Estado",
    "Storage": "Almacenamiento",
    "Time zone": "Zona horaria",
    "True Tone": "True Tone",
    "Uptime": "Tiempo de actividad",
    "Version": "Versión",
    "Virtual size": "Tamaño virtual",
    "Wired": "Cableado",
    "action.copy": "Copiar",
    "action.recheck": "Volver a ejecutar comprobaciones",
    "action.refresh": "Actualizar",
    "action.save": "Guardar",
    "action.share": "Compartir",
    "action.shareSection": "Compartir sección",
    "app.title": "iOS Info App",
    "common.cancel": "Cancelar",
    "compat.category.emulator": "Emulador",
    "compat.category.tool": "Herramienta",
    "compat.editNote": "Nota",
    "compat.ios": "iOS %@",
    "compat.jitUnknown": "Requisito JIT sin confirmar",
    "compat.needsJit": "necesita JIT",
    "compat.note.dolphin": "GameCube/Wii. iOS 26.6+ no es compatible.",
    "compat.note.dukex": "N64. En iOS 27 solo en A13/A14/M1.",
    "compat.note.flycast": "Dreamcast. En 26+ usa el fork de iOS 26.",
    "compat.note.macios": "Ejecuta macOS en dispositivos Apple Silicon.",
    "compat.note.ppsspp": "PSP. Funciona sin JIT, pero mucho más rápido con él.",
    "compat.note.sidestore": "SideStore 0.6.2 tiene JIT integrado en el dispositivo (iOS 16 y anteriores o dispositivos antiguos no TXM).",
    "compat.note.stikdebug": "El último StikDebug funciona en iOS 17.4–18.x y tiene un fix para iOS 26/27.",
    "compat.note.trollstore": "TrollStore 14.0b2–16.6.1, 16.7RC, 17.0. Lanza apps con JIT.",
    "compat.note.utm": "Máquinas virtuales basadas en QEMU. JIT da un gran aumento de velocidad.",
    "compat.notePlaceholder": "Añadir una nota…",
    "compat.search": "Buscar apps…",
    "compat.title": "Compatibilidad",
    "compat.visit": "Visitar el sitio web",
    "details.search": "Buscar",
    "expl.allowJit": "El entitlement 'com.apple.security.cs.allow-jit' permite el mapeo JIT del proceso (memoria RW→RX).",
    "expl.allowJitShort": "Permite el mapeo JIT (RW→RX) para el proceso.",
    "expl.availableMemory": "Bytes aún disponibles hasta alcanzar el límite de memoria sucia. El límite ≈ este valor + phys_footprint actual.",
    "expl.csopsDebugged": "CS_DEBUGGED se establece cuando el proceso está o estuvo depurado: el núcleo permite entonces JIT mediante el depurador.",
    "expl.csopsFlags": "Banderas brutas de csops(CS_OPS_STATUS): los atributos de firma de código del proceso, decodificados con nombres oficiales en modo Dev.",
    "expl.dynamicCodesigning": "'dynamic-codesigning' permite cambiar los estados de firma de código en tiempo de ejecución: requisito previo para JIT.",
    "expl.extendedVA": "'com.apple.developer.kernel.extended-virtual-addressing' permite el direccionamiento virtual extendido (más allá de 4 GB).",
    "expl.extendedVAShort": "Permite el direccionamiento virtual extendido.",
    "expl.extendedVerdict": "YES solo si el límite medido es ≥ 70 % de la RAM. Los entitlements por sí solos no demuestran un límite elevado: los dispositivos antiguos los ignoran.",
    "expl.getTaskAllow": "Permite que los depuradores (p. ej. Xcode) se adjunten a esta app: requisito previo para JIT mediante depurador.",
    "expl.increasedDebug": "'com.apple.developer.kernel.increased-debugging-memory-limit' eleva además el límite de memoria para llamadas de depuración.",
    "expl.increasedDebugShort": "Eleva el límite de memoria para llamadas de depuración.",
    "expl.increasedMemory": "'com.apple.developer.kernel.increased-memory-limit' eleva el límite de memoria del proceso.",
    "expl.increasedMemoryShort": "Eleva el límite de memoria del proceso.",
    "expl.jailbreakHints": "Rutas típicas de jailbreak/rootful. Si existen o las rutas del sistema son escribibles, apunta a un jailbreak.",
    "expl.jitEntitled": "Sysctl del núcleo: '1' significa que el proceso está marcado como autorizado para JIT.",
    "expl.memoryLimit": "Límite de memoria estimado del proceso = os_proc_available_memory() + phys_footprint. El valor predeterminado de iOS es aproximadamente la mitad de la RAM.",
    "expl.physFootprint": "Huella de memoria física del proceso (el valor fiable desde iOS 13).",
    "expl.ptraced": "P_TRACED indica un depurador ptrace activo: permite JIT en el núcleo.",
    "expl.ramShare": "Proporción del límite de memoria estimado respecto a la RAM física. ≥ 70 % significa un límite elevado.",
    "expl.resident": "Parte del proceso actualmente en RAM (no intercambiada).",
    "expl.rlimitAS": "Límite de recursos para el tamaño de dirección virtual. 'cur' = actual, 'max' = límite duro, 'unlimited' = sin límite.",
    "expl.rlimitData": "Límite de recursos para el heap / segmento de datos del proceso.",
    "expl.virtual": "Espacio de direcciones reservado virtualmente: puede ser mucho mayor que la RAM.",
    "history.clear": "Borrar historial",
    "history.clearConfirm": "¿Eliminar todo el historial?",
    "history.empty": "Aún no hay entradas",
    "history.export": "Exportar",
    "history.export.csv": "CSV",
    "history.export.json": "JSON",
    "history.range": "Período",
    "history.range.all": "Todo",
    "history.range.month": "30 días",
    "history.range.today": "Hoy",
    "history.range.week": "7 días",
    "history.save": "Guardar en Archivos…",
    "history.title": "Historial JIT",
    "iOS version": "Versión de iOS",
    "live.available": "Disponible",
    "live.cpu": "CPU",
    "live.memory": "Memoria",
    "live.requires16": "Los gráficos en vivo requieren iOS 16+.",
    "live.thermal": "Térmico",
    "mode.dev": "Dev",
    "mode.expert": "Experto",
    "mode.normal": "Normal",
    "network.chart": "Velocidad de red",
    "network.download": "Desc.",
    "network.header": "Red",
    "network.interfaces": "Interfaces",
    "network.noData": "No hay datos de tráfico disponibles.",
    "network.rate": "Velocidad",
    "network.received": "Recibido",
    "network.sent": "Enviado",
    "network.status.cellular": "Celular",
    "network.status.ethernet": "Ethernet",
    "network.status.offline": "Sin conexión",
    "network.status.online": "En línea",
    "network.status.requiresConnection": "Requiere conexión",
    "network.status.unknown": "Desconocido",
    "network.status.wifi": "Wi-Fi",
    "network.total": "Total",
    "network.upload": "Sub.",
    "notif.logChanged": "Estado cambiado",
    "notif.logInitial": "Estado inicial",
    "phys_footprint": "phys_footprint",
    "power.appState": "Estado de la app",
    "power.lowPower": "Modo de bajo consumo",
    "power.state.active": "activa",
    "power.state.background": "en segundo plano",
    "power.state.inactive": "inactiva",
    "power.thermal": "Estado térmico",
    "power.thermal.critical": "crítico",
    "power.thermal.fair": "moderado",
    "power.thermal.nominal": "nominal",
    "power.thermal.serious": "grave",
    "processes.count": "%d procesos",
    "processes.cpu": "CPU",
    "processes.memory": "RAM",
    "processes.name": "Nombre",
    "processes.restricted": "iOS bloquea la lista de procesos en la sandbox. Solo se ve esta app: la lista completa requiere jailbreak.",
    "processes.self": "esta app",
    "processes.sortBy": "Ordenar por",
    "processes.state.idle": "inactivo",
    "processes.state.running": "en ejecución",
    "processes.state.sleeping": "en reposo",
    "processes.state.stopped": "detenido",
    "processes.state.uninterruptible": "ininterrumpible",
    "processes.state.unknown": "desconocido",
    "processes.state.zombie": "zombie",
    "processes.terminate": "Terminar",
    "processes.terminateConfirm": "¿Terminar « %@ » (PID %d)?",
    "processes.terminateFailed": "No se pudo terminar el proceso.",
    "rec.jbGeneral": "Con jailbreak: JIT suele concederse automáticamente (p. ej. « Allow JIT in Apps » de Dopamine). Si no, adjunta debugserver a la app.",
    "rec.jitActive": "JIT está activo: no hace falta nada más.",
    "rec.reason": "Motivo: %@",
    "rec.soc.checkra1n": "Tu chip %@ es compatible con checkra1n (A8–A11) – jailbreak semi-tethered como alternativa.",
    "rec.soc.stikFixApplies": "Tu chip %@ está cubierto por el fix de StikDebug 3.1.6: el script JIT en el dispositivo debería funcionar.",
    "rec.soc.stikFixNotApplies": "Tu chip %@ NO está cubierto por el fix de StikDebug: se necesita un script por app (A15+/M2+) o una herramienta de PC.",
    "rec.tipGetTaskAllow": "Tu app sideload debe incluir el entitlement get-task-allow; si no, las herramientas JIT no pueden adjuntarse.",
    "rec.v15": "iOS 15.x: instala TrollStore y lanza la app con JIT. Alternativa: AltJIT mediante AltServer.",
    "rec.v16": "iOS 16.x: instala TrollStore y lanza la app con JIT. Alternativa: AltJIT mediante AltServer o SideStore.",
    "rec.v170": "iOS 17.0: instala TrollStore (bug de CoreTrust) y lanza la app con JIT.",
    "rec.v173": "iOS 17.0.1–17.3: usa SideJITServer (PC/Mac) o AltJIT mediante pymobiledevice3 en macOS.",
    "rec.v174": "iOS 17.4–17.9: usa StikJIT / StikDebug – JIT en el dispositivo (empareja una vez con un PC, requiere LocalDevVPN).",
    "rec.v18": "iOS 18.0–18.3: usa StikJIT / StikDebug, SideStore o JITStreamer-EB – JIT en el dispositivo o por red.",
    "rec.v184": "iOS 18.4–18.7: usa StikDebug o SideStore 0.6.2 – activadores JIT en el dispositivo (empareja una vez con un PC).",
    "rec.v26": "iOS 26: usa StikDebug (actualizado para iOS 26) o SideStore 0.6.2 – JIT en el dispositivo. Solo unas pocas apps funcionan en iOS 26.6+.",
    "rec.v27": "iOS 27: JIT solo es posible con StikDebug (3.1.6+, compatible con A13/A14/M1) con un script por app: solo funcionan unas pocas apps (UTM, MeloNX, maciOS, Geode, Manic EMU, ARMSX2, DukeX).",
    "rec.xcode": "Universal: lanza la app desde Xcode en un Mac (get-task-allow) y adjunta el depurador – activa JIT sin jailbreak.",
    "recommendation.title": "Recomendación JIT",
    "report.format.json": "JSON",
    "report.format.markdown": "Markdown",
    "report.history": "## Historial JIT",
    "report.jitReason": "Motivo JIT: %@",
    "report.liveSnapshot": "## Instantánea en vivo",
    "report.memoryReason": "Motivo de memoria extendida: %@",
    "report.off": "OFF",
    "report.on": "ON",
    "report.processes": "Procesos",
    "report.processesRestricted": "iOS restringe la lista de procesos: solo se ve esta app.",
    "report.recommendation": "## Recomendación",
    "report.saveJson": "Guardar como JSON…",
    "report.saveMarkdown": "Guardar como Markdown…",
    "report.shareAccessibility": "Compartir informe",
    "report.title": "Informe JIT Info – %@",
    "section.app": "App",
    "section.battery": "Batería",
    "section.batteryPower": "Batería y energía",
    "section.cpuRam": "CPU y RAM",
    "section.entitlements": "Entitlements",
    "section.kernel": "Núcleo",
    "section.locale": "Locale",
    "section.memory": "Memoria",
    "section.network": "Red",
    "section.power": "Energía",
    "section.screen": "Pantalla",
    "section.storage": "Almacenamiento",
    "section.system": "Sistema",
    "settings.appearance": "Apariencia",
    "settings.appearance.dark": "Oscuro",
    "settings.appearance.light": "Claro",
    "settings.appearance.system": "Sistema",
    "settings.haptics": "Retroalimentación háptica",
    "settings.language": "Idioma",
    "settings.language.system": "Sistema",
    "settings.mode": "Modo",
    "settings.privacy": "Todos los datos se procesan localmente en este dispositivo. No se envía nada.",
    "settings.title": "Ajustes",
    "settings.updateInterval": "Intervalo de actualización",
    "status.battery": "Batería",
    "status.battery.charging": "Cargando",
    "status.battery.full": "Completa",
    "status.battery.low": "Batería por debajo del 20 %: las sesiones JIT pueden terminar abruptamente cuando el dispositivo se duerme.",
    "status.battery.unknown": "Desconocido",
    "status.battery.unplugged": "Sin cargar",
    "status.card.extendedMemory": "Memoria extendida",
    "status.jitChecks": "Comprobaciones JIT",
    "status.live": "Live",
    "status.memoryChecks": "Comprobaciones de memoria extendida",
    "status.off": "OFF",
    "status.on": "ON",
    "status.title": "Estado",
    "status.updated": "Actualizado",
    "status.uptime": "Tiempo de actividad",
    "tab.details": "Detalles",
    "tab.network": "Red",
    "tab.processes": "Procesos",
    "tab.settings": "Ajustes",
    "tab.status": "Estado",
]

